T1 = readtable('iris.txt')
T2 = readtable('glass.txt')
subplot(3, 2, 1)
hist(T1.SL)
title('iris.txt - SL')
subplot(3, 2, 2)
hist(T1.PL)
title('iris.txt - PL')
subplot(3, 2, 3)
hist(T1.PW)
title('iris.txt - PW')
subplot(3, 2, 4)
hist(T2.Mg)
title('iris.txt - Mg')
subplot(3, 2, 5)
hist(T2.Si)
title('iris.txt - Si')
subplot(3, 2, 6)
hist(T2.Ca)
title('iris.txt - Ca')